# Generated by Django 5.2.1 on 2025-05-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aperto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aperto',
                'verbose_name_plural': 'Apertos',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Percurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Percurso',
                'verbose_name_plural': 'Tipos de Percurso',
            },
        ),
        migrations.CreateModel(
            name='Angulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.aperto')),
            ],
            options={
                'verbose_name': 'Ângulo',
                'verbose_name_plural': 'Ângulos',
            },
        ),
        migrations.CreateModel(
            name='Plano_Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.aperto')),
            ],
            options={
                'verbose_name': 'Plano de Trabalho',
                'verbose_name_plural': 'Planos de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('pasta_programas', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('programador', models.CharField(max_length=100)),
                ('tempo_projeto', models.CharField(max_length=100)),
                ('centro_bloco', models.CharField(max_length=100)),
                ('referencia_z', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('observacao', models.CharField(max_length=100)),
                ('aperto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.aperto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('setup_inicio', models.DateField()),
                ('setup_hora_ini', models.CharField(max_length=100)),
                ('setup_termino', models.DateField()),
                ('setup_hora_ter', models.CharField(max_length=100)),
                ('usina_inicio', models.DateField()),
                ('usina_hora_ini', models.CharField(max_length=100)),
                ('usina_termino', models.DateField()),
                ('usina_hora_ter', models.CharField(max_length=100)),
                ('programa', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=100)),
                ('ferramenta_o', models.FloatField(blank=True, null=True)),
                ('ferramenta_rc', models.FloatField(blank=True, null=True)),
                ('ferramenta_rib', models.FloatField(blank=True, null=True)),
                ('ferramenta_alt', models.FloatField(blank=True, null=True)),
                ('z_min', models.FloatField(blank=True, default=0, null=True)),
                ('lat_2d', models.FloatField(blank=True, null=True)),
                ('lat_sob_esp', models.FloatField(blank=True, null=True)),
                ('vert_sob_esp', models.FloatField(blank=True, null=True)),
                ('lat_passo', models.FloatField(blank=True, null=True)),
                ('vert_passo', models.FloatField(blank=True, null=True)),
                ('tol', models.FloatField(blank=True, default=0, null=True)),
                ('rot', models.FloatField(blank=True, default=0, null=True)),
                ('av', models.FloatField(blank=True, default=0, null=True)),
                ('corte', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('fresa', models.CharField(max_length=100)),
                ('sup', models.CharField(max_length=100)),
                ('medicao', models.CharField(max_length=100)),
                ('rubrica', models.BooleanField(default=False)),
                ('angulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.angulo')),
                ('plano_trab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.plano_trabalho')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.projeto')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.referencia')),
                ('tipo_percurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.tipo_percurso')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
