# Generated by Django 5.2.1 on 2025-05-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('pasta_programas', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('programador', models.CharField(max_length=100)),
                ('aperto', models.CharField(max_length=100)),
                ('tempo_projeto', models.CharField(max_length=100)),
                ('centro_bloco', models.CharField(max_length=100)),
                ('referencia_z', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('observacao', models.CharField(max_length=100)),
                ('setup_inicio', models.DurationField(blank=True)),
                ('setup_hora_ini', models.DurationField(blank=True)),
                ('setup_termino', models.DurationField(blank=True)),
                ('setup_hora_ter', models.DurationField(blank=True)),
                ('usina_inicio', models.DurationField(blank=True)),
                ('usina_hora_ini', models.DurationField(blank=True)),
                ('usina_termino', models.DurationField(blank=True)),
                ('usina_hora_ter', models.DurationField(blank=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('processo', models.AutoField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=100)),
                ('tipo_percurso', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=100)),
                ('ferramenta_o', models.FloatField(blank=True, null=True)),
                ('ferramenta_rc', models.FloatField(blank=True, null=True)),
                ('ferramenta_rib', models.FloatField(blank=True, null=True)),
                ('ferramenta_alt', models.FloatField(blank=True, null=True)),
                ('z_min', models.FloatField(blank=True, default=0, null=True)),
                ('lat_2d', models.FloatField(blank=True, null=True)),
                ('lat_sob_esp', models.FloatField(blank=True, null=True)),
                ('vert_sob_esp', models.FloatField(blank=True, null=True)),
                ('lat_passo', models.FloatField(blank=True, null=True)),
                ('vert_passo', models.FloatField(blank=True, null=True)),
                ('tol', models.FloatField(blank=True, default=0, null=True)),
                ('rot', models.FloatField(blank=True, default=0, null=True)),
                ('av', models.FloatField(blank=True, default=0, null=True)),
                ('angulo', models.CharField(max_length=100)),
                ('plano_trab', models.CharField(max_length=100)),
                ('corte', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('fresa', models.CharField(max_length=100)),
                ('sup', models.CharField(max_length=100)),
                ('medicao', models.CharField(blank=True, max_length=100, null=True)),
                ('rubrica', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_simoldes.projeto')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
