# Generated by Django 5.2.1 on 2025-05-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_simoldes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='processo',
            new_name='id',
        ),
    ]
