# Generated by Django 5.2.1 on 2025-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_simoldes', '0002_rename_processo_processo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='setup_hora_ini',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='setup_hora_ter',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='setup_inicio',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='setup_termino',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usina_hora_ini',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usina_hora_ter',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usina_inicio',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usina_termino',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
