# Generated by Django 5.2.1 on 2025-05-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_simoldes', '0003_alter_projeto_setup_hora_ini_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='setup_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='setup_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usina_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usina_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
