# Generated by Django 5.2.1 on 2025-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_simoldes', '0004_alter_projeto_setup_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='rubrica_montador',
            field=models.BooleanField(default=False),
        ),
    ]
